Repository smh-algorithms/algorithms, pull requests merged in 2021-02, with the labels that each got.

#35 4주차 문제 제안
  src/week4.human-readable-duration/README.md
  src/week4.menu-renewal/README.md
  src/week4.no-repeat-please/README.md
  src/week4.predict-the-winner/README.md
  src/week4.restore-ip-addresses/README.md
  src/week4.rgb-to-hex/README.md
  src/week4.word-search/README.md
Labels: challenges

#42 findawayer | week5 제안
  src/week5.buying-cookies/README.md
  src/week5.n-queen/README.md
  src/week5.network/README.md
  src/week5.parallel-universe/README.md
  src/week5.rotate-image/README.md
  src/week5.search-a-2d-matrix-ii/README.md
  src/week5.target-number/README.md
Labels: challenges

#44 week6 제안
  src/week6.bad-users/README.md
  src/week6.chess-triangle/README.md
  src/week6.decode-string/README.md
  src/week6.expression-by-n/README.md
  src/week6.minimum-window-substring/README.md
  src/week6.subsets/README.md
  src/week6.tree-collect/README.md
  src/week6.tree-collect/test.js
Labels: 🐾 challenges

#46 findawayer | week1-2 교정
  src/week1.dual-priority-queue/findawayer.js
  src/week1.merge-intervals/findawayer.js
  src/week2.sorting-insertion-sort/findawayer.js
Labels: 🐞 fix

#33 lunar- week1.fibonacci 풀이
  src/week1.fibonacci/lunar.js
Labels: 🧪 solution

#47 week7 제안
  src/week7.best-album/README.md
  src/week7.first-bad-version/README.md
  src/week7.hangul-unicode-from-jamo/README.md
  src/week7.most-profit-assigning-work/README.md
  src/week7.ones-and-zeros/README.md
  src/week7.product-of-consecutive-fib-numbers/README.md
  src/week7.speed-cameras/README.md
Labels: 🐾 challenges
